name: CI run
run-name: CI triggered by ${{ github.actor }} for ${{ github.head_ref }}
on:
  pull_request:
  workflow_dispatch:
    # paths:
    #   - themes/**
    #   - .github/**
    #   - package*.json
    #   - palette.css
jobs:
  package-theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install -g @vscode/vsce
      - name: Package theme
        run: vsce package
