on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy-to-marketplace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install @vscode/vsce
      - name: Package
        run: vsce package
      - name: Publish
        run: vsce publish
