name: Test Build and Scripts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Test theme generation
        run: npm run generate-themes

      - name: Verify version script (major)
        run: |
          node scripts/update-version.js --major
          # Verify package.json was updated correctly
          if ! grep -q '"version": "2.0.0"' package.json; then
            echo "Version update failed"
            exit 1
          fi

      - name: Verify version script (minor)
        run: |
          node scripts/update-version.js --minor
          # Verify package.json was updated correctly
          if ! grep -q '"version": "2.1.0"' package.json; then
            echo "Version update failed"
            exit 1
          fi

      - name: Verify version script (patch)
        run: |
          node scripts/update-version.js --patch
          # Verify package.json was updated correctly
          if ! grep -q '"version": "2.1.1"' package.json; then
            echo "Version update failed"
            exit 1
          fi

      - name: Test VSIX package creation
        run: vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v3
        with:
          name: theme-extension
          path: "*.vsix"
